/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-29 13:50:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class _005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1724728830000L));
    _jspx_dependants.put("jar:file:/C:/Users/lsh9084/Desktop/dddd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/farmstory/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>농작물이야기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/footer.css\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header-wrapper\">\r\n");
      out.write("		<div class=\"header-logo-box\">\r\n");
      out.write("			<div class=\"header-logo\"  onclick=\"location.href='/farmstory'\">\r\n");
      out.write("				<div class=\"logo-link-box\">\r\n");
      out.write("					<div class=\"logo-link\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/farmstory\">Home</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>|</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/farmstory/member/login.do\">로그인</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>|</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/farmstory/register.do\">회원가입</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>|</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/farmstory/community/qna.html\">고객센터</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"logo-add-box\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-gubun-box\">\r\n");
      out.write("			<div class=\"menu-1\"></div>\r\n");
      out.write("			<div class=\"menu-2\"></div>\r\n");
      out.write("			<div class=\"menu-3\"></div>\r\n");
      out.write("			<div class=\"menu-4\"></div>\r\n");
      out.write("			<div class=\"menu-5\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-menu-box\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"menu-gubun\"></div>\r\n");
      out.write("				<a href=\"/farmstory/introduction/hello.do\">\r\n");
      out.write("					<div class=\"menu-1 menu\"></div>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"menu-gubun\"></div>\r\n");
      out.write("				<a href=\"/farmstory//market/list.do\">\r\n");
      out.write("					<div class=\"menu-2 menu\">\r\n");
      out.write("						<img src=\"../images/head_menu_badge.png\" alt=\"badge\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"menu-gubun\"></div>\r\n");
      out.write("				<a href=\"/farmstory/article/list.do?group=croptalk&cate=story\">\r\n");
      out.write("					<div class=\"menu-3 menu\"></div>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"menu-gubun\"></div>\r\n");
      out.write("				<a href=\"/farmstory/article/list.do?group=event&cate=info\">\r\n");
      out.write("					<div class=\"menu-4 menu\"></div>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"menu-gubun\"></div>\r\n");
      out.write("				<a href=\"/farmstory/article/list.do?group=community&cate=notice\">\r\n");
      out.write("					<div class=\"menu-5 menu\"></div>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-bottom-img\">\r\n");
      out.write("			<div class=\"header-bottom-comm\">\r\n");
      out.write("				<img src=\"/farmstory/images/sub_top_tit_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${group}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".png\" alt=\"bottom-img5\">  <!-- 수정 -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
