/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-30 02:18:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.market;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1724728830000L));
    _jspx_dependants.put("jar:file:/C:/Users/lsh9084/Desktop/dddd/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/farmstory/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>ì¥ë³´ê¸°</title>\r\n");
      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	window.onload = function() {\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		const total = document.getElementsByClassName('total')[0];\r\n");
      out.write("		const stock = document.getElementsByClassName('stock')[0];\r\n");
      out.write("		const price = document.getElementsByClassName('price')[0];\r\n");
      out.write("		const del = document.getElementsByClassName('frame18-text48')[0];\r\n");
      out.write("		const realdel = parseInt(del.value,10);\r\n");
      out.write("		\r\n");
      out.write("		del.value = (parseInt(del.value,10))+'원';\r\n");
      out.write("		\r\n");
      out.write("		price.value = (parseInt(price.value,10))+'원';\r\n");
      out.write("		if(parseInt(price.value,10) <= 30000){\r\n");
      out.write("			total.value = (parseInt(price.value,10)+parseInt(del.value,10))+'원';\r\n");
      out.write("			del.value = realdel + '원';\r\n");
      out.write("		} else{\r\n");
      out.write("			total.value = (parseInt(price.value,10))+'원';\r\n");
      out.write("			del.value = 0 +'원';\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		stock.oninput = function() {\r\n");
      out.write("	\r\n");
      out.write("			const t_value =(parseInt(price.value,10));\r\n");
      out.write("			const s_value = stock.value;\r\n");
      out.write("				\r\n");
      out.write("			if(t_value*stock.value < 30000){\r\n");
      out.write("				total.value = (t_value*stock.value)+parseInt(del.value,10)+'원';\r\n");
      out.write("				del.value = realdel + '원';\r\n");
      out.write("				\r\n");
      out.write("			}else{\r\n");
      out.write("				total.value = (t_value*stock.value)+'원';\r\n");
      out.write("				del.value = 0 +'원';\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/view.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/footer.css\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/_header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"main-wrapper\">\r\n");
      out.write("        <div class=\"sidebar-box\">\r\n");
      out.write("            <div class=\"sidebar-logo-box\">\r\n");
      out.write("                <div class=\"sidebar-logo\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sidebar-bg-box\">\r\n");
      out.write("                <div class=\"sidebar-item-1\"></div>\r\n");
      out.write("                <div class=\"sidebar-item-2\"></div>\r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sidebar-gubun-box\"></div>\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"main-box\">\r\n");
      out.write("            <div class=\"main-title-box\">\r\n");
      out.write("                <div class=\"main-title\"></div>\r\n");
      out.write("                <div class=\"main-nav-box\">\r\n");
      out.write("                    <div class=\"nav-icon-box\">\r\n");
      out.write("                        <div class=\"nav-icon\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"nav-tit-1\">Home</div>\r\n");
      out.write("                    <div class=\"nav-latest-icon\">></div>\r\n");
      out.write("                    <div class=\"nav-tit-2\">장보기</div>\r\n");
      out.write("                    <div class=\"nav-latest-icon\">></div>\r\n");
      out.write("                    <div class=\"nav-tit-3\">장보기</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"main-gubun-box\">\r\n");
      out.write("                <div class=\"frame18-article\">\r\n");
      out.write("                    <span class=\"frame18-text08\"><span>기본정보</span></span>\r\n");
      out.write("                    <form action=\"/farmstory/market/cart.do\" method=\"post\" class=\"frame18-container1\">\r\n");
      out.write("                      <img class=\"frame18-marketitemthumbjpg\" src=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.prod_file[0].path}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.prod_file[0].filename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" />\r\n");
      out.write("                      <div class=\"frame18-table\">\r\n");
      out.write("                        <div class=\"frame18-body\">\r\n");
      out.write("                          <div class=\"frame18-row2\">\r\n");
      out.write("                            <span class=\"frame18-text37\"><span>상품명</span></span>\r\n");
      out.write("                            <span class=\"frame18-text39\"><input name=\"prod_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.prod_name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"frame18-row3\">\r\n");
      out.write("                            <span class=\"frame18-text41\"><span>상품코드</span></span>\r\n");
      out.write("                            <span class=\"frame18-text43\"><input name=\"prod_idx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.prod_idx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ></span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"frame18-row4\">\r\n");
      out.write("                            <span class=\"frame18-text45\"><span>배송비</span></span>\r\n");
      out.write("                            <div class=\"frame18-data4\">\r\n");
      out.write("                              <span class=\"frame18-text47\">\r\n");
      out.write("                                <input class=\"frame18-text48\" name=\"deliveryFee\" value=\"0\" >\r\n");
      out.write("                                <span>3만원 이상 무료배송</span>\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"frame18-row5\">\r\n");
      out.write("                            <span class=\"frame18-text50\"><span>판매가격</span></span>\r\n");
      out.write("                            <span class=\"frame18-text52\"><input name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"price\"></span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"frame18-row6\">\r\n");
      out.write("                            <span class=\"frame18-text54\"><span>구매수량</span></span>\r\n");
      out.write("                            <div class=\"frame18-data-input\">                     \r\n");
      out.write("                               <input type=\"number\" name=\"quantity\" class=\"stock\" min=\"0\" value=\"1\"/> \r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"frame18-row7\">\r\n");
      out.write("                            <span class=\"frame18-text57\"><span>합계</span></span>\r\n");
      out.write("                            <span class=\"frame18-text59\"><input name=\"sum\" class=\"total\" value =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ></span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <button type=\"submit\" class=\"frame18-link5\">\r\n");
      out.write("                        <span class=\"frame18-text61\"><span>장바구니</span></span>\r\n");
      out.write("                      </button>\r\n");
      out.write("                      <div class=\"frame18-link6\">\r\n");
      out.write("                        <span class=\"frame18-text63\"><span>바로구매</span></span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("			\r\n");
      out.write("                    <span class=\"frame18-text10\"><span>상품설명</span></span>\r\n");
      out.write("                    \r\n");
      out.write("                   <img src=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.prod_file[1].path}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.prod_file[1].filename}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" class=\"frame18-marketdetailsamplejpg\">\r\n");
      out.write("                    <span class=\"frame18-text12\"><span>배송정보</span></span>\r\n");
      out.write("                    <span class=\"frame18-text14\">\r\n");
      out.write("                      <span>\r\n");
      out.write("                         입금하신 이후 택배송장번호는 SMS(문자서비스)를 통해 고객님께 안내해드립니다.\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"frame18-text16\">êµí/ë°í</span>\r\n");
      out.write("                    <div class=\"frame18-table-body\">\r\n");
      out.write("                      <div class=\"frame18-row\">\r\n");
      out.write("                        <div class=\"frame18-data\">\r\n");
      out.write("                          <span class=\"frame18-text18\">\r\n");
      out.write("                             <span>교환 반품이 가능한 경우</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"frame18-data1\">\r\n");
      out.write("                          <div class=\"frame18-list2\">\r\n");
      out.write("                            <span class=\"frame18-text20\">\r\n");
      out.write("                              <span>팜스토리 상품에 하자가 있거나 불량인 경우</span>\r\n");
      out.write("                              <br />\r\n");
      out.write("                              <span>채소, 과일, 양곡등의 식품은 만1일 이내</span>\r\n");
      out.write("                              <br />\r\n");
      out.write("                              <span>\r\n");
      out.write("                                기타 상품은 수령일로부터 영업일 기준 일주일 이내\r\n");
      out.write("                              </span>\r\n");
      out.write("                              <br />\r\n");
      out.write("                              <span>\r\n");
      out.write("                                받으신 상품이 표시사항과 다른 경우에는 받으신 날로부터\r\n");
      out.write("                                일주일 이내\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"frame18-row1\">\r\n");
      out.write("                        <div class=\"frame18-data2\">\r\n");
      out.write("                          <span class=\"frame18-text28\">\r\n");
      out.write("                             <span>교환 반품이 불가능한 경우</span>\r\n");
      out.write("                          </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"frame18-data3\">\r\n");
      out.write("                          <div class=\"frame18-list3\">\r\n");
      out.write("                            <span class=\"frame18-text30\">\r\n");
      out.write("                              <span>\r\n");
      out.write("                                신선 식품의 경우 단순히 마음에 들지 않는 경우\r\n");
      out.write("                              </span>\r\n");
      out.write("                              <br />\r\n");
      out.write("                              <span>\r\n");
      out.write("                                단순 변심으로 상품이 가치가 훼손돼서 판매가 어려운\r\n");
      out.write("                                경우\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <span class=\"frame18-text34\"/>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                 \r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/_footer.jsp", out, false);
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
