/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-29 13:33:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>로그인</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/login.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/footer.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    .login-links {\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	const success= ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("	\r\n");
      out.write("	if(success == 100){\r\n");
      out.write("		alert('로그인에 실패했습니다. \\n다시 한번 아이디, 비밀번호를 확인 하시기 바랍니다.');\r\n");
      out.write("	} else if(success == 101){\r\n");
      out.write("		alert('정상적으로 로그아웃 되었습니다.');\r\n");
      out.write("	} else if(success == 102){\r\n");
      out.write("		alert('먼저 로그인을 하셔야 합니다.');\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header-wrapper\">\r\n");
      out.write("        <div class=\"header-logo-box\">\r\n");
      out.write("            <div class=\"header-logo\">\r\n");
      out.write("                <div class=\"logo-link-box\">\r\n");
      out.write("                    <div class=\"logo-link\">\r\n");
      out.write("                        <div>Home</div>\r\n");
      out.write("                        <div>|</div>\r\n");
      out.write("                        <div>로그인</div>\r\n");
      out.write("                        <div>|</div>\r\n");
      out.write("                        <div>회원가입</div>\r\n");
      out.write("                        <div>|</div>\r\n");
      out.write("                        <div>고객센터</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-gubun-box\">\r\n");
      out.write("            <div class=\"menu-1\"></div>\r\n");
      out.write("            <div class=\"menu-2\"></div>\r\n");
      out.write("            <div class=\"menu-3\"></div>\r\n");
      out.write("            <div class=\"menu-4\"></div>\r\n");
      out.write("            <div class=\"menu-5\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-menu-box\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-1 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-2 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-3 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-4 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-5 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-wrapper\">\r\n");
      out.write("        <div class=\"main-box\">\r\n");
      out.write("            <section class=\"login\">\r\n");
      out.write("                <form action=\"/farmstory/member/login.do\" method=\"POST\">\r\n");
      out.write("                    <table border=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"/farmstory/images/login_ico_id.png\" alt=\"아이디\"></td>\r\n");
      out.write("                            <td><input type=\"text\" name=\"uid\" placeholder=\"아이디 입력\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"/farmstory/images/login_ico_pw.png\" alt=\"비밀번호\"></td>\r\n");
      out.write("                            <td><input type=\"password\" name=\"pass\" placeholder=\"비밀번호 입력\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <input type=\"submit\" value=\"로그인\" class=\"btnLogin\">\r\n");
      out.write("                    <div class=\"login-links\">\r\n");
      out.write("                        <a href=\"/farmstory/member/findId.do\">아이디찾기 |</a>\r\n");
      out.write("                        <a href=\"/farmstory/member/findPass.do\">비밀번호찾기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>	\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3>회원 로그인 안내</h3>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        아직 회원이 아니시면 회원으로 가입하세요.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <a href=\"/farmstory/member/terms.do\">회원가입</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/_footer.jsp", out, false);
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
