/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-29 13:47:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/register.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/farmstory/css/footer.css\">\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"/farmstory/js/postcode.js\"></script>\r\n");
      out.write("<script src=\"/farmstory/js/validation.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header-wrapper\">\r\n");
      out.write("        <div class=\"header-logo-box\">\r\n");
      out.write("            <div class=\"header-logo\">\r\n");
      out.write("                <div class=\"logo-link-box\">\r\n");
      out.write("                    <div class=\"logo-link\">\r\n");
      out.write("                        <div>Home</div>\r\n");
      out.write("                        <div>|</div>\r\n");
      out.write("                        <div>로그인</div>\r\n");
      out.write("                        <div>|</div>\r\n");
      out.write("                        <div>회원가입</div>\r\n");
      out.write("                        <div>|</div>\r\n");
      out.write("                        <div>고객센터</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"logo-add-box\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-gubun-box\">\r\n");
      out.write("            <div class=\"menu-1\"></div>\r\n");
      out.write("            <div class=\"menu-2\"></div>\r\n");
      out.write("            <div class=\"menu-3\"></div>\r\n");
      out.write("            <div class=\"menu-4\"></div>\r\n");
      out.write("            <div class=\"menu-5\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-menu-box\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-1 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-2 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-3 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-4 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"menu-gubun\"></div>\r\n");
      out.write("                <div class=\"menu-5 menu\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-box\">\r\n");
      out.write("                        <section class=\"register\">\r\n");
      out.write("                <form action=\"/farmstory/member/register.do\" method=\"POST\">\r\n");
      out.write("                    <table border=\"1\">\r\n");
      out.write("                        <caption>사이트 이용정보 입력</caption>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>아이디</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" name=\"uid\" placeholder=\"아이디 입력\"/>\r\n");
      out.write("                                <button  type=\"button\" id=\"btnCheckUid\"><img src=\"/farmstory/images/chk_id.gif\" alt=\"\"></button>\r\n");
      out.write("                                <span class=\"resultId\"></span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>비밀번호</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"password\" name=\"pass1\" placeholder=\"비밀번호 입력\"/>                            \r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>비밀번호 확인</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"password\" name=\"pass2\" placeholder=\"비밀번호 확인 입력\"/>\r\n");
      out.write("                                <span class=\"resultPass\"></span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <table border=\"1\">\r\n");
      out.write("                        <caption>개인정보 입력</caption>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>이름</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" name=\"name\" placeholder=\"이름 입력\"/>  \r\n");
      out.write("                                <span class=\"resultName\"></span>                          \r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>별명</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <p>공백없이 한글, 영문, 숫자만 입력가능</p>\r\n");
      out.write("                                <input type=\"text\" name=\"nick\" placeholder=\"별명 입력\"/>\r\n");
      out.write("                                <span class=\"resultNick\"></span>                            \r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>E-Mail</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                 <input type=\"email\" name=\"email\" placeholder=\"이메일 입력\"/>\r\n");
      out.write("                       			<button type=\"button\" id=\"btnSendEmail\"><img src=\"/farmstory/images/chk_auth.gif\" alt=\"인증번호 받기\"/></button>\r\n");
      out.write("                       			<span class=\"resultEmail\"></span>\r\n");
      out.write("                       			<div class=\"auth\">\r\n");
      out.write("                           		<input type=\"text\" name=\"auth\" placeholder=\"인증번호 입력\"/>\r\n");
      out.write("                           		<button type=\"button\" id=\"btnAuthEmail\"><img src=\"/farmstory/images/chk_confirm.gif\" alt=\"확인\"/></button>\r\n");
      out.write("                       </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>휴대폰</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"text\" name=\"hp\" placeholder=\"- 포함 13자리 입력\" minlength=\"13\" maxlength=\"13\" />\r\n");
      out.write("                            	 <span class=\"resultHp\"></span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>주소</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <input type=\"text\" name=\"zip\" id=\"zip\" placeholder=\"우편번호\" readonly/>                                \r\n");
      out.write("                                    <button type=\"button\" class=\"btnZip\" onclick=\"postcode()\"><img src=\"/farmstory/images/chk_post.gif\" alt=\"\"></button>\r\n");
      out.write("                                </div>                            \r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <input type=\"text\" name=\"addr1\" id=\"addr1\" placeholder=\"주소를 검색하세요.\" readonly/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <input type=\"text\" name=\"addr2\" id=\"addr2\" placeholder=\"상세주소를 입력하세요.\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("    \r\n");
      out.write("                    <div>\r\n");
      out.write("                        <a href=\"/farmstory/member/login.do\" class=\"btnCancel\">취소</a>\r\n");
      out.write("                        <input type=\"submit\"   class=\"btnSubmit\" value=\"회원가입\"/>\r\n");
      out.write("                    </div>    \r\n");
      out.write("                </form>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/_footer.jsp", out, false);
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
